name: Release

on:
  push:
    branches:
      - v1.x # Trigger workflow on push to the main branch

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    # Run ktra action
    - name: Run ktra
      uses: patrickoppel/ktra/.github/actions@develop
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
